version: "3"

services:
  db:
    image: mysql:5.7
    container_name: hp-api-mysql
    restart: always
    volumes:
      - ../mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - vars.env

  api:
    build: .
    container_name: hp-api
    restart: always
    env_file:
      - vars.env
    volumes:
      - ./static:/code/static
    ports:
      - 8001:8001
    working_dir: /code
    depends_on:
      - db

  ui:
    build: https://github.com/HiddenPreprints/web-ui.git
    container_name: hp-ui
    restart: always
    environment:
      - API_URL=http://nginx:8000
    ports:
      - 3000:3000
    depends_on:
      - api

  nginx:
    image: nginx:1.17
    container_name: hp-api-nginx
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - api
